### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by tsmock** [TommiContursi/MTB-TrailMap-JOSM-Style#1]
From [JOSM CI](https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/jdk=JDK11/10685/testReport/junit/org.openstreetmap.josm.gui.preferences.map/MapPaintPreferenceTestIT/MTB_Trailmap__MTB_Difficulty__uphill_difficulty__path_width__visibility_and_surface____https___github_com_TommiContursi_MTB_TrailMap_JOSM_Style_blob_main_MTB_Trailmap_JOSM_map_style_mapcss/):
> `MTB Trailmap (MTB Difficulty, uphill difficulty, path width, visibility and surface) => [] [Mappaint style "standard" (MTB Trailmap (MTB Difficulty, uphill difficulty, path width, visibility and surface)) icon "presets/barrier/barrier_kissing_gate.svg" not found., Mappaint style "standard" (MTB Trailmap (MTB Difficulty, uphill difficulty, path width, visibility and surface)) icon "presets/barrier/barrier_cycle_barrier.svg" not found.] ==> expected: <true> but was: <false>`

Specific missing icons -> the icon you _probably_ wanted:
* `presets/barrier/barrier_kissing_gate.svg` -> `presets/barrier/kissing_gate.svg`
* `presets/barrier/barrier_cycle_barrier.svg` -> `presets/barrier/cycle_barrier.svg`

**Comment by TommiContursi** [comment]
Thanks for noticing! I corrected the icon paths and updated the file. Both of those obstacles are quite rare in my area; it was easy to overlook the missing icons.
